ðŸš€ Starting CLAM training...
no change     /home/liannello/miniconda3/condabin/conda
no change     /home/liannello/miniconda3/bin/conda
no change     /home/liannello/miniconda3/bin/conda-env
no change     /home/liannello/miniconda3/bin/activate
no change     /home/liannello/miniconda3/bin/deactivate
no change     /home/liannello/miniconda3/etc/profile.d/conda.sh
no change     /home/liannello/miniconda3/etc/fish/conf.d/conda.fish
no change     /home/liannello/miniconda3/shell/condabin/Conda.psm1
no change     /home/liannello/miniconda3/shell/condabin/conda-hook.ps1
no change     /home/liannello/miniconda3/lib/python3.13/site-packages/xontrib/conda.xsh
no change     /home/liannello/miniconda3/etc/profile.d/conda.csh
no change     /home/liannello/.bashrc
No action taken.
Traceback (most recent call last):
  File "/home/liannello/MLIAProject/MLIAProject/CLAM/create_splits_seq.py", line 46, in <module>
    dataset = Generic_WSI_Classification_Dataset(csv_path = 'MLIAProject/CLAM/dataset_csv/MLIA_Project_CLAM.csv',
  File "/home/liannello/MLIAProject/MLIAProject/CLAM/dataset_modules/dataset_generic.py", line 65, in __init__
    slide_data = pd.read_csv(csv_path)
  File "/home/liannello/miniconda3/envs/clam_latest/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/liannello/miniconda3/envs/clam_latest/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/liannello/miniconda3/envs/clam_latest/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/liannello/miniconda3/envs/clam_latest/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/liannello/miniconda3/envs/clam_latest/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'MLIAProject/CLAM/dataset_csv/MLIA_Project_CLAM.csv'

ERROR conda.cli.main_run:execute(125): `conda run python /home/liannello/MLIAProject/MLIAProject/CLAM/create_splits_seq.py --task MLIA_Project --seed 1 --k 1 --val_frac 0.2 --test_frac 0.2` failed. (See above for error)
